# Generated by Django 4.1.3 on 2022-11-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('num_man', models.IntegerField()),
                ('num_women', models.IntegerField()),
            ],
            options={
                'db_table': 'numcar',
            },
        ),
        migrations.CreateModel(
            name='NumEvCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('num_evcar', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
            options={
                'db_table': 'numevcar',
            },
        ),
    ]
