# Generated by Django 4.1.3 on 2022-11-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumEvCar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region2', models.CharField(max_length=20)),
                ('num_evcar2', models.IntegerField()),
                ('percent2', models.IntegerField()),
            ],
            options={
                'db_table': 'numevcar2',
            },
        ),
    ]
