# Generated by Django 4.1.3 on 2022-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapg', '0002_numevcar2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=20)),
                ('two', models.IntegerField()),
            ],
            options={
                'db_table': 'test1',
            },
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=20)),
                ('two', models.IntegerField()),
            ],
            options={
                'db_table': 'test2',
            },
        ),
    ]
