# Generated by Django 4.1.2 on 2022-11-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_pw',
        ),
    ]
