# Generated by Django 4.1.2 on 2022-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.CharField(max_length=300),
        ),
    ]
