# Generated by Django 4.1.1 on 2022-11-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
